[package]
name = "spine_render"
version = "0.1.0"
authors = ["Johann Tuffe <tafia973@gmail.com>"]

[dependencies]
glium = "*"
image = "*"
clock_ticks = "*"

[dependencies.spine_tiny]
git = "https://github.com/tafia/spine-rs.git"
branch = "skeleton"
