[package]
name = "spine_render"
version = "0.1.0"
authors = ["Johann Tuffe <tafia973@gmail.com>"]

[dependencies]
glium = "0.13"
image = "0.7"
time = "0.1"
docopt = "0.6"
rustc-serialize = "0.3"

[dependencies.spine_tiny]
git = "https://github.com/tomaka/spine-rs"
